splash = 0

wallpaper {
  monitor = HDMI-A-1
  path = /home/ben/Pictures/background2.jpg
  fit_mode = cover
}

wallpaper {
  monitor = DP-2
  path = /home/ben/Pictures/background2.jpg
  fit_mode = cover
}

wallpaper {
  monitor = DP-3
  path = /home/ben/Pictures/background2.jpg
  fit_mode = cover
}
