general {
  disable_loading_bar = true
  hide_cursor = true
  grace = 0
}

background {
  monitor =
  path = screenshot
  blur_passes = 3
  blur_size = 7
  noise = 0.010
  contrast = 1.080
  brightness = 0.650
  vibrancy = 0.180
  vibrancy_darkness = 0.150
}

input-field {
  monitor =
  size = 280, 52
  outline_thickness = 1
  dots_size = 0.180
  dots_spacing = 0.220
  dots_center = true
  fade_on_empty = false
  font_color = rgba(c6d0f5ff)
  inner_color = rgba(101010cc)
  outer_color = rgba(c6d0f555)
  check_color = rgba(8caaeeff)
  fail_color = rgba(e78284ff)
  placeholder_text = <span foreground="##737994">Password</span>
  fail_text = <span foreground="##e78284">Try again</span>
  hide_input = false
  rounding = 6
  position = 0, -42
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] date +"%H:%M"
  color = rgba(c6d0f5ff)
  font_size = 72
  font_family = JetBrainsMono Nerd Font
  position = 0, 86
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:60000] date +"%A, %d %B"
  color = rgba(737994ff)
  font_size = 16
  font_family = JetBrainsMono Nerd Font
  position = 0, 26
  halign = center
  valign = center
}
